### ISSUE TITLE
Main last child won't move to grid-column 2, grid-row 2 independently.

### ISSUE THREAD

**Issue by sent0007** [sent0007/components-on-a-grid#1]
When I try to move the figures to separate the grid areas, they stick together vertically and won't separate. It doesn't seem to want to let me target the second figure. I've tried :nth-child :last-child :first-child and nothing seems to work. Any ideas? Thank you!

![Screen Shot 2020-09-20 at 12 58 33 AM](https://user-images.githubusercontent.com/55108791/93694690-d0242400-fadc-11ea-8a34-4c8ac7bee858.png)

https://github.com/sent0007/components-on-a-grid/blob/a262576f5d323e2d534c0d3179897e282f2693c6/css/main.css#L71-L81

@MacKenzieRose

**Comment by MacKenzieRose** [comment]
Ah! The solution for this will require a little restructuring, so bear with me! You have the right idea :)

One of the problems lies in how grid-template-areas are defined under the body tag. Each section needs a different name. Because Science Labs and International Space Station need to exist in 2 different columns, or two different areas, we need another name, in addition to main for `grid-template-areas` to work properly.

Secondly, we want to add `display: contents` to your `main` tag in your css. This will make your `figure` tags act like they are directly part of the grid.

And then, finally, we will need to target that second `figure` tag with the new grid-template-area name, instead of main.

Let me know if this helps; if not, tag me again 😸

**Comment by sent0007** [comment]
Thanks for the precise reply, It really helps.

I believe, it's written how you described in the last comment but, now I'm having trouble keeping the 1st column static. Whenever the screen size changes so does the grid column and the content within it.

<img width="999" alt="Screen Shot 2020-09-21 at 4 46 29 PM" src="https://user-images.githubusercontent.com/55108791/93820276-ea6c1800-fc2a-11ea-91c1-eea6bfdf5675.png">

https://github.com/sent0007/components-on-a-grid/blob/332df8274fc1742d3a2dbcfc64a9fd4158d5fd9e/css/main.css#L83-L88

https://github.com/sent0007/components-on-a-grid/blob/332df8274fc1742d3a2dbcfc64a9fd4158d5fd9e/css/main.css#L13-L23

I'm stumped because the second column doesn't have the issue.. Sorry for the late comment. 

@MacKenzieRose
